/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionToken = IDL.Text;
export const RecordId = IDL.Nat;
export const BlogPostInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'slug' : IDL.Text,
  'featuredImageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const EventItemInput = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'registrationLink' : IDL.Text,
  'location' : IDL.Text,
});
export const GalleryEntryInput = IDL.Record({
  'studentName' : IDL.Text,
  'order' : IDL.Nat,
  'universityAdmitted' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
  'destinationCountry' : IDL.Text,
  'visaStatus' : IDL.Text,
});
export const JobOpeningInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'department' : IDL.Text,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
});
export const PartnerUniversity = IDL.Record({
  'id' : RecordId,
  'country' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'website' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const ServiceItemInput = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'ctaLink' : IDL.Text,
});
export const TeamMemberInput = IDL.Record({
  'bio' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const TestimonialInput = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'text' : IDL.Text,
  'university' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
  'rating' : IDL.Nat,
  'course' : IDL.Text,
  'youtubeUrl' : IDL.Opt(IDL.Text),
});
export const Achievement = IDL.Record({
  'id' : RecordId,
  'metric' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const TimelineEntry = IDL.Record({
  'id' : RecordId,
  'year' : IDL.Text,
  'description' : IDL.Text,
  'milestone' : IDL.Text,
});
export const AboutPageContent = IDL.Record({
  'mission' : IDL.Text,
  'companyStory' : IDL.Text,
  'imageUrl' : IDL.Text,
  'achievements' : IDL.Vec(Achievement),
  'vision' : IDL.Text,
  'timeline' : IDL.Vec(TimelineEntry),
});
export const JobOpening = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'department' : IDL.Text,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
});
export const AdminDashboardStats = IDL.Record({
  'pending' : IDL.Nat,
  'totalLeads' : IDL.Nat,
  'thisMonth' : IDL.Nat,
});
export const CountryFAQ = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const CountryTopUniversity = IDL.Record({
  'name' : IDL.Text,
  'ranking' : IDL.Text,
});
export const CountryInfo = IDL.Record({
  'order' : IDL.Nat,
  'acceptanceRate' : IDL.Text,
  'visaSteps' : IDL.Vec(IDL.Text),
  'faqs' : IDL.Vec(CountryFAQ),
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'tuition' : IDL.Text,
  'averageCost' : IDL.Text,
  'flagImage' : IDL.Text,
  'processingTime' : IDL.Text,
  'heroImage' : IDL.Text,
  'popularCourses' : IDL.Vec(IDL.Text),
  'topUniversities' : IDL.Vec(CountryTopUniversity),
  'workOpportunities' : IDL.Text,
  'prPathway' : IDL.Text,
  'intakeMonths' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
  'scholarships' : IDL.Vec(IDL.Text),
  'visaSuccessRate' : IDL.Text,
});
export const PageSection = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'sectionType' : IDL.Text,
  'imageUrl' : IDL.Text,
  'items' : IDL.Vec(IDL.Text),
});
export const PageContent = IDL.Record({
  'heroImageUrl' : IDL.Text,
  'metaDescription' : IDL.Text,
  'bodyContent' : IDL.Text,
  'title' : IDL.Text,
  'isActive' : IDL.Bool,
  'heroSubheadline' : IDL.Text,
  'sections' : IDL.Vec(PageSection),
  'heroHeadline' : IDL.Text,
  'pageId' : IDL.Text,
});
export const PartnershipTypeItem = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
});
export const BeOurPartnerContent = IDL.Record({
  'formDescription' : IDL.Text,
  'partnershipTypes' : IDL.Vec(PartnershipTypeItem),
  'generalBenefits' : IDL.Vec(IDL.Text),
  'heroImage' : IDL.Text,
  'heroSubheadline' : IDL.Text,
  'heroHeadline' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : RecordId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : Timestamp,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Nat,
  'updatedAt' : Timestamp,
  'featuredImageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'branch2Name' : IDL.Text,
  'email' : IDL.Text,
  'branch1Name' : IDL.Text,
  'branch3Name' : IDL.Text,
  'address1' : IDL.Text,
  'address2' : IDL.Text,
  'address3' : IDL.Text,
  'phone1' : IDL.Text,
  'phone2' : IDL.Text,
  'phone3' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : RecordId,
  'inquiryType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});
export const CounselingBooking = IDL.Record({
  'id' : RecordId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'countryInterests' : IDL.Vec(IDL.Text),
  'preferredTime' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
  'educationLevel' : IDL.Text,
});
export const FAQ = IDL.Record({
  'id' : RecordId,
  'question' : IDL.Text,
  'order' : IDL.Nat,
  'answer' : IDL.Text,
});
export const CountryUniversity = IDL.Record({
  'id' : RecordId,
  'name' : IDL.Text,
  'tuition' : IDL.Text,
  'website' : IDL.Text,
  'logoUrl' : IDL.Text,
  'ranking' : IDL.Text,
});
export const VisaStep = IDL.Record({
  'id' : RecordId,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
});
export const CostBreakdown = IDL.Record({
  'miscellaneous' : IDL.Text,
  'food' : IDL.Text,
  'transport' : IDL.Text,
  'totalMonthly' : IDL.Text,
  'accommodation' : IDL.Text,
});
export const CountryDetailContent = IDL.Record({
  'heroImageUrl' : IDL.Text,
  'workRights' : IDL.Text,
  'faqs' : IDL.Vec(FAQ),
  'universities' : IDL.Vec(CountryUniversity),
  'heroSubtitle' : IDL.Text,
  'visaProcess' : IDL.Vec(VisaStep),
  'countrySlug' : IDL.Text,
  'prOpportunities' : IDL.Text,
  'popularCourses' : IDL.Vec(IDL.Text),
  'costOfLiving' : CostBreakdown,
  'heroTitle' : IDL.Text,
  'scholarships' : IDL.Vec(IDL.Text),
  'whyStudyHere' : IDL.Text,
});
export const DemoClassBooking = IDL.Record({
  'id' : RecordId,
  'name' : IDL.Text,
  'testType' : IDL.Text,
  'email' : IDL.Text,
  'preferredTime' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});
export const EventItem = IDL.Record({
  'id' : RecordId,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'registrationLink' : IDL.Text,
  'location' : IDL.Text,
});
export const FacebookReviewsBadge = IDL.Record({
  'reviewUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
  'rating' : IDL.Text,
  'reviewCount' : IDL.Text,
});
export const FooterLink = IDL.Record({
  'url' : IDL.Text,
  'linkLabel' : IDL.Text,
});
export const FooterSocialLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const GoogleReviewsBadge = IDL.Record({
  'reviewUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
  'rating' : IDL.Text,
  'reviewCount' : IDL.Text,
});
export const EduLoanPartner = IDL.Record({
  'id' : IDL.Text,
  'websiteUrl' : IDL.Text,
  'name' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const OfficeLocation = IDL.Record({
  'id' : IDL.Text,
  'city' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const FooterContent = IDL.Record({
  'facebookReviewsBadge' : FacebookReviewsBadge,
  'serviceLinks' : IDL.Vec(FooterLink),
  'socialLinks' : IDL.Vec(FooterSocialLink),
  'googleReviewsBadge' : GoogleReviewsBadge,
  'copyrightText' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'quickLinks' : IDL.Vec(FooterLink),
  'countryLinks' : IDL.Vec(FooterLink),
  'eduLoanPartners' : IDL.Vec(EduLoanPartner),
  'officeLocations' : IDL.Vec(OfficeLocation),
});
export const FreeCounselingBenefitPoint = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const FreeCounselingContent = IDL.Record({
  'heroImageUrl' : IDL.Text,
  'formDescription' : IDL.Text,
  'benefitPoints' : IDL.Vec(FreeCounselingBenefitPoint),
  'ctaText' : IDL.Text,
  'heroSubheadline' : IDL.Text,
  'heroHeadline' : IDL.Text,
});
export const GalleryEntry = IDL.Record({
  'id' : IDL.Nat,
  'studentName' : IDL.Text,
  'order' : IDL.Nat,
  'universityAdmitted' : IDL.Text,
  'createdAt' : IDL.Int,
  'imageUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
  'destinationCountry' : IDL.Text,
  'visaStatus' : IDL.Text,
});
export const HeroContent = IDL.Record({
  'yearsExperience' : IDL.Text,
  'headline' : IDL.Text,
  'studentsGuided' : IDL.Text,
  'subheadline' : IDL.Text,
  'universityPartnerships' : IDL.Text,
  'visaSuccessRate' : IDL.Text,
});
export const HomeSocialLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const HomeSectionPoint = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const HomeSectionsContent = IDL.Record({
  'universityMarqueeEnabled' : IDL.Bool,
  'whyChooseUsHeadline' : IDL.Text,
  'ctaBannerSubheadline' : IDL.Text,
  'footerSocialLinks' : IDL.Vec(HomeSocialLink),
  'whyChooseUsPoints' : IDL.Vec(HomeSectionPoint),
  'ctaBannerButtonText' : IDL.Text,
  'footerDescription' : IDL.Text,
  'ctaBannerHeadline' : IDL.Text,
  'eventsDisplayCount' : IDL.Nat,
  'testimonialsDisplayCount' : IDL.Nat,
});
export const ImmigrationConsultation = IDL.Record({
  'id' : RecordId,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'visaType' : IDL.Text,
  'preferredTime' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});
export const ImmigrationVisa = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'successRate' : IDL.Text,
  'description' : IDL.Text,
  'processingTime' : IDL.Text,
  'visaType' : IDL.Text,
  'imageUrl' : IDL.Text,
  'documentsRequired' : IDL.Vec(IDL.Text),
  'requirements' : IDL.Vec(IDL.Text),
  'eligibilityCriteria' : IDL.Vec(IDL.Text),
});
export const JobApplication = IDL.Record({
  'id' : IDL.Nat,
  'applicantName' : IDL.Text,
  'positionApplied' : IDL.Text,
  'submittedAt' : IDL.Int,
  'coverLetter' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'jobOpeningId' : IDL.Nat,
  'resumeUrl' : IDL.Text,
});
export const LeadershipMember = IDL.Record({
  'id' : RecordId,
  'bio' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const LifeAtValmikiGalleryImage = IDL.Record({
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
});
export const LifeAtValmikiPerk = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const LifeAtValmikiContent = IDL.Record({
  'heroImageUrl' : IDL.Text,
  'galleryImages' : IDL.Vec(LifeAtValmikiGalleryImage),
  'missionText' : IDL.Text,
  'heroSubheadline' : IDL.Text,
  'cultureDescription' : IDL.Text,
  'perks' : IDL.Vec(LifeAtValmikiPerk),
  'heroHeadline' : IDL.Text,
});
export const NewsletterSubscription = IDL.Record({
  'id' : RecordId,
  'email' : IDL.Text,
  'timestamp' : Timestamp,
});
export const PageHeroContent = IDL.Record({
  'headline' : IDL.Text,
  'imageUrl' : IDL.Text,
  'subheadline' : IDL.Text,
  'pageId' : IDL.Text,
});
export const BeOurPartnerInquiry = IDL.Record({
  'id' : IDL.Nat,
  'contactName' : IDL.Text,
  'partnershipType' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const ServiceFAQ = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const ServiceProcessStep = IDL.Record({
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const ServiceDetailContent = IDL.Record({
  'faqs' : IDL.Vec(ServiceFAQ),
  'ctaButtonText' : IDL.Text,
  'overview' : IDL.Text,
  'processSteps' : IDL.Vec(ServiceProcessStep),
  'heroImage' : IDL.Text,
  'ctaText' : IDL.Text,
  'heroSubheadline' : IDL.Text,
  'serviceId' : IDL.Text,
  'heroHeadline' : IDL.Text,
  'eligibilityCriteria' : IDL.Vec(IDL.Text),
  'whyChooseValmiki' : IDL.Vec(IDL.Text),
  'whatIsIncluded' : IDL.Vec(IDL.Text),
});
export const ServiceItem = IDL.Record({
  'id' : RecordId,
  'features' : IDL.Vec(IDL.Text),
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'ctaLink' : IDL.Text,
});
export const ProcessStep = IDL.Record({
  'id' : RecordId,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const ScholarshipInfo = IDL.Record({
  'id' : RecordId,
  'name' : IDL.Text,
  'deadline' : IDL.Text,
  'eligibility' : IDL.Text,
  'amount' : IDL.Text,
});
export const StudyAbroadContent = IDL.Record({
  'headline' : IDL.Text,
  'intakeInfo' : IDL.Text,
  'processSteps' : IDL.Vec(ProcessStep),
  'imageUrl' : IDL.Text,
  'introduction' : IDL.Text,
  'scholarships' : IDL.Vec(ScholarshipInfo),
});
export const TeamMember = IDL.Record({
  'id' : RecordId,
  'bio' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const BatchTiming = IDL.Record({
  'id' : RecordId,
  'endDate' : IDL.Text,
  'enrolled' : IDL.Nat,
  'capacity' : IDL.Nat,
  'schedule' : IDL.Text,
  'startDate' : IDL.Text,
});
export const TestPrepExam = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Text,
  'scoreRange' : IDL.Text,
  'cost' : IDL.Text,
  'successRate' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'batchTimings' : IDL.Vec(BatchTiming),
});
export const TestimonialItem = IDL.Record({
  'id' : RecordId,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'text' : IDL.Text,
  'university' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
  'rating' : IDL.Nat,
  'course' : IDL.Text,
  'youtubeUrl' : IDL.Opt(IDL.Text),
});
export const VisaEligibilityResult = IDL.Record({
  'id' : RecordId,
  'age' : IDL.Nat,
  'country' : IDL.Text,
  'education' : IDL.Text,
  'testScores' : IDL.Text,
  'visaType' : IDL.Text,
  'timestamp' : Timestamp,
  'workExperienceYears' : IDL.Nat,
  'resultPercentage' : IDL.Nat,
});
export const WebsiteTheme = IDL.Record({
  'backgroundColor' : IDL.Text,
  'primaryColor' : IDL.Text,
  'buttonTextColor' : IDL.Text,
  'accentColor' : IDL.Text,
  'buttonColor' : IDL.Text,
  'secondaryColor' : IDL.Text,
  'footerBgColor' : IDL.Text,
  'footerTextColor' : IDL.Text,
  'headingTextColor' : IDL.Text,
  'bodyTextColor' : IDL.Text,
});
export const SubmissionResult = IDL.Record({
  'id' : RecordId,
  'timestamp' : Timestamp,
});
export const JobApplicationInput = IDL.Record({
  'applicantName' : IDL.Text,
  'positionApplied' : IDL.Text,
  'coverLetter' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'jobOpeningId' : IDL.Nat,
  'resumeUrl' : IDL.Text,
});
export const BeOurPartnerInquiryInput = IDL.Record({
  'contactName' : IDL.Text,
  'partnershipType' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBatchTiming' : IDL.Func(
      [
        SessionToken,
        IDL.Text,
        IDL.Record({
          'endDate' : IDL.Text,
          'enrolled' : IDL.Nat,
          'capacity' : IDL.Nat,
          'schedule' : IDL.Text,
          'startDate' : IDL.Text,
        }),
      ],
      [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
      [],
    ),
  'addBlogPost' : IDL.Func(
      [SessionToken, BlogPostInput],
      [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
      [],
    ),
  'addCountry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addEvent' : IDL.Func(
      [IDL.Text, EventItemInput],
      [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
      [],
    ),
  'addGalleryEntry' : IDL.Func(
      [SessionToken, GalleryEntryInput],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'addJobOpening' : IDL.Func(
      [SessionToken, JobOpeningInput],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'addPartnerUniversity' : IDL.Func(
      [SessionToken, PartnerUniversity],
      [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
      [],
    ),
  'addService' : IDL.Func(
      [IDL.Text, ServiceItemInput],
      [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
      [],
    ),
  'addTeamMember' : IDL.Func(
      [IDL.Text, TeamMemberInput],
      [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
      [],
    ),
  'addTestimonial' : IDL.Func(
      [IDL.Text, TestimonialInput],
      [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
      [],
    ),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : SessionToken, 'err' : IDL.Text })],
      [],
    ),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'deleteBatchTiming' : IDL.Func(
      [SessionToken, IDL.Text, RecordId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteBlogPost' : IDL.Func(
      [SessionToken, RecordId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteCountry' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteEvent' : IDL.Func(
      [IDL.Text, RecordId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteGalleryEntry' : IDL.Func(
      [SessionToken, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteJobApplication' : IDL.Func(
      [SessionToken, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteJobOpening' : IDL.Func(
      [SessionToken, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deletePartnerUniversity' : IDL.Func(
      [SessionToken, RecordId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteService' : IDL.Func(
      [IDL.Text, RecordId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteTeamMember' : IDL.Func(
      [IDL.Text, RecordId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteTestimonial' : IDL.Func(
      [IDL.Text, RecordId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAboutPageContent' : IDL.Func([], [AboutPageContent], ['query']),
  'getActiveJobOpenings' : IDL.Func([], [IDL.Vec(JobOpening)], ['query']),
  'getAdminDashboardStats' : IDL.Func([], [AdminDashboardStats], ['query']),
  'getAllCountries' : IDL.Func([], [IDL.Vec(CountryInfo)], ['query']),
  'getAllPageContents' : IDL.Func([], [IDL.Vec(PageContent)], ['query']),
  'getBeOurPartnerContent' : IDL.Func(
      [],
      [IDL.Opt(BeOurPartnerContent)],
      ['query'],
    ),
  'getBlogPostById' : IDL.Func([RecordId], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getCounselingBookings' : IDL.Func(
      [],
      [IDL.Vec(CounselingBooking)],
      ['query'],
    ),
  'getCountryDetail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CountryDetailContent)],
      ['query'],
    ),
  'getCountryDetailAll' : IDL.Func(
      [],
      [IDL.Vec(CountryDetailContent)],
      ['query'],
    ),
  'getCountryDetailBySlug' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CountryDetailContent)],
      ['query'],
    ),
  'getCountryInfo' : IDL.Func([IDL.Text], [IDL.Opt(CountryInfo)], ['query']),
  'getCountryInfoAll' : IDL.Func([], [IDL.Vec(CountryInfo)], ['query']),
  'getDemoClassBookings' : IDL.Func([], [IDL.Vec(DemoClassBooking)], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(EventItem)], ['query']),
  'getFooterContent' : IDL.Func([], [FooterContent], ['query']),
  'getFreeCounselingContent' : IDL.Func([], [FreeCounselingContent], ['query']),
  'getGalleryEntries' : IDL.Func([], [IDL.Vec(GalleryEntry)], ['query']),
  'getHeroContent' : IDL.Func([], [HeroContent], ['query']),
  'getHomeSectionsContent' : IDL.Func([], [HomeSectionsContent], ['query']),
  'getImmigrationConsultations' : IDL.Func(
      [],
      [IDL.Vec(ImmigrationConsultation)],
      ['query'],
    ),
  'getImmigrationVisaById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ImmigrationVisa)],
      ['query'],
    ),
  'getImmigrationVisas' : IDL.Func([], [IDL.Vec(ImmigrationVisa)], ['query']),
  'getJobApplications' : IDL.Func(
      [SessionToken],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getJobOpenings' : IDL.Func([], [IDL.Vec(JobOpening)], ['query']),
  'getLeadershipMembers' : IDL.Func([], [IDL.Vec(LeadershipMember)], ['query']),
  'getLifeAtValmikiContent' : IDL.Func([], [LifeAtValmikiContent], ['query']),
  'getNewsletterSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(NewsletterSubscription)],
      ['query'],
    ),
  'getPageContent' : IDL.Func([IDL.Text], [IDL.Opt(PageContent)], ['query']),
  'getPageHeroContent' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PageHeroContent)],
      ['query'],
    ),
  'getPartnerInquiries' : IDL.Func(
      [SessionToken],
      [IDL.Vec(BeOurPartnerInquiry)],
      ['query'],
    ),
  'getPartnerUniversities' : IDL.Func(
      [],
      [IDL.Vec(PartnerUniversity)],
      ['query'],
    ),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getServiceDetail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ServiceDetailContent)],
      ['query'],
    ),
  'getServices' : IDL.Func([], [IDL.Vec(ServiceItem)], ['query']),
  'getStudyAbroadContent' : IDL.Func([], [StudyAbroadContent], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getTestPrepExamById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TestPrepExam)],
      ['query'],
    ),
  'getTestPrepExams' : IDL.Func([], [IDL.Vec(TestPrepExam)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(TestimonialItem)], ['query']),
  'getVisaEligibilityResults' : IDL.Func(
      [],
      [IDL.Vec(VisaEligibilityResult)],
      ['query'],
    ),
  'getVisibleGalleryEntries' : IDL.Func([], [IDL.Vec(GalleryEntry)], ['query']),
  'getWebsiteTheme' : IDL.Func([], [WebsiteTheme], ['query']),
  'reorderCountries' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'reorderPartnerUniversities' : IDL.Func(
      [SessionToken, IDL.Vec(RecordId)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setBeOurPartnerContent' : IDL.Func(
      [SessionToken, BeOurPartnerContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setServiceDetail' : IDL.Func(
      [SessionToken, ServiceDetailContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SubmissionResult],
      [],
    ),
  'submitCounselingBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [SubmissionResult],
      [],
    ),
  'submitDemoClassBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SubmissionResult],
      [],
    ),
  'submitImmigrationConsultation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SubmissionResult],
      [],
    ),
  'submitJobApplication' : IDL.Func(
      [JobApplicationInput],
      [JobApplication],
      [],
    ),
  'submitPartnerInquiry' : IDL.Func(
      [BeOurPartnerInquiryInput],
      [SubmissionResult],
      [],
    ),
  'submitVisaEligibility' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [SubmissionResult],
      [],
    ),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [SubmissionResult], []),
  'toggleBlogPostPublish' : IDL.Func(
      [SessionToken, RecordId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'toggleGalleryEntryVisibility' : IDL.Func(
      [SessionToken, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateAboutPageContent' : IDL.Func(
      [SessionToken, AboutPageContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateBatchTiming' : IDL.Func(
      [
        SessionToken,
        IDL.Text,
        RecordId,
        IDL.Record({
          'endDate' : IDL.Text,
          'enrolled' : IDL.Nat,
          'capacity' : IDL.Nat,
          'schedule' : IDL.Text,
          'startDate' : IDL.Text,
        }),
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateBlogPost' : IDL.Func(
      [SessionToken, RecordId, BlogPostInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateContactInfo' : IDL.Func(
      [IDL.Text, ContactInfo],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCountryDetailBySlug' : IDL.Func(
      [SessionToken, CountryDetailContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCountryInfo' : IDL.Func(
      [IDL.Text, CountryInfo],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateEvent' : IDL.Func(
      [IDL.Text, RecordId, EventItemInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateFooterContent' : IDL.Func(
      [IDL.Text, FooterContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateFreeCounselingContent' : IDL.Func(
      [IDL.Text, FreeCounselingContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateGalleryEntry' : IDL.Func(
      [SessionToken, IDL.Nat, GalleryEntryInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateHeroContent' : IDL.Func(
      [IDL.Text, HeroContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateHomeSectionsContent' : IDL.Func(
      [IDL.Text, HomeSectionsContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateImmigrationVisa' : IDL.Func(
      [SessionToken, ImmigrationVisa],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateJobOpening' : IDL.Func(
      [SessionToken, IDL.Nat, JobOpeningInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateLeadershipMembers' : IDL.Func(
      [SessionToken, IDL.Vec(LeadershipMember)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateLifeAtValmikiContent' : IDL.Func(
      [IDL.Text, LifeAtValmikiContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updatePageContent' : IDL.Func(
      [SessionToken, IDL.Text, PageContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updatePageHeroContent' : IDL.Func(
      [IDL.Text, PageHeroContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updatePartnerUniversity' : IDL.Func(
      [SessionToken, RecordId, PartnerUniversity],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateService' : IDL.Func(
      [IDL.Text, RecordId, ServiceItemInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateStudyAbroadContent' : IDL.Func(
      [SessionToken, StudyAbroadContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateTeamMember' : IDL.Func(
      [IDL.Text, RecordId, TeamMemberInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateTestPrepExam' : IDL.Func(
      [SessionToken, TestPrepExam],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateTestimonial' : IDL.Func(
      [IDL.Text, RecordId, TestimonialInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateWebsiteTheme' : IDL.Func(
      [IDL.Text, WebsiteTheme],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'verifyAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionToken = IDL.Text;
  const RecordId = IDL.Nat;
  const BlogPostInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'slug' : IDL.Text,
    'featuredImageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const EventItemInput = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'registrationLink' : IDL.Text,
    'location' : IDL.Text,
  });
  const GalleryEntryInput = IDL.Record({
    'studentName' : IDL.Text,
    'order' : IDL.Nat,
    'universityAdmitted' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
    'destinationCountry' : IDL.Text,
    'visaStatus' : IDL.Text,
  });
  const JobOpeningInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'department' : IDL.Text,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
  });
  const PartnerUniversity = IDL.Record({
    'id' : RecordId,
    'country' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'website' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const ServiceItemInput = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'ctaLink' : IDL.Text,
  });
  const TeamMemberInput = IDL.Record({
    'bio' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const TestimonialInput = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'text' : IDL.Text,
    'university' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
    'rating' : IDL.Nat,
    'course' : IDL.Text,
    'youtubeUrl' : IDL.Opt(IDL.Text),
  });
  const Achievement = IDL.Record({
    'id' : RecordId,
    'metric' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const TimelineEntry = IDL.Record({
    'id' : RecordId,
    'year' : IDL.Text,
    'description' : IDL.Text,
    'milestone' : IDL.Text,
  });
  const AboutPageContent = IDL.Record({
    'mission' : IDL.Text,
    'companyStory' : IDL.Text,
    'imageUrl' : IDL.Text,
    'achievements' : IDL.Vec(Achievement),
    'vision' : IDL.Text,
    'timeline' : IDL.Vec(TimelineEntry),
  });
  const JobOpening = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'department' : IDL.Text,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
  });
  const AdminDashboardStats = IDL.Record({
    'pending' : IDL.Nat,
    'totalLeads' : IDL.Nat,
    'thisMonth' : IDL.Nat,
  });
  const CountryFAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const CountryTopUniversity = IDL.Record({
    'name' : IDL.Text,
    'ranking' : IDL.Text,
  });
  const CountryInfo = IDL.Record({
    'order' : IDL.Nat,
    'acceptanceRate' : IDL.Text,
    'visaSteps' : IDL.Vec(IDL.Text),
    'faqs' : IDL.Vec(CountryFAQ),
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'tuition' : IDL.Text,
    'averageCost' : IDL.Text,
    'flagImage' : IDL.Text,
    'processingTime' : IDL.Text,
    'heroImage' : IDL.Text,
    'popularCourses' : IDL.Vec(IDL.Text),
    'topUniversities' : IDL.Vec(CountryTopUniversity),
    'workOpportunities' : IDL.Text,
    'prPathway' : IDL.Text,
    'intakeMonths' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
    'scholarships' : IDL.Vec(IDL.Text),
    'visaSuccessRate' : IDL.Text,
  });
  const PageSection = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'sectionType' : IDL.Text,
    'imageUrl' : IDL.Text,
    'items' : IDL.Vec(IDL.Text),
  });
  const PageContent = IDL.Record({
    'heroImageUrl' : IDL.Text,
    'metaDescription' : IDL.Text,
    'bodyContent' : IDL.Text,
    'title' : IDL.Text,
    'isActive' : IDL.Bool,
    'heroSubheadline' : IDL.Text,
    'sections' : IDL.Vec(PageSection),
    'heroHeadline' : IDL.Text,
    'pageId' : IDL.Text,
  });
  const PartnershipTypeItem = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
  });
  const BeOurPartnerContent = IDL.Record({
    'formDescription' : IDL.Text,
    'partnershipTypes' : IDL.Vec(PartnershipTypeItem),
    'generalBenefits' : IDL.Vec(IDL.Text),
    'heroImage' : IDL.Text,
    'heroSubheadline' : IDL.Text,
    'heroHeadline' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : RecordId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : Timestamp,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Nat,
    'updatedAt' : Timestamp,
    'featuredImageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'branch2Name' : IDL.Text,
    'email' : IDL.Text,
    'branch1Name' : IDL.Text,
    'branch3Name' : IDL.Text,
    'address1' : IDL.Text,
    'address2' : IDL.Text,
    'address3' : IDL.Text,
    'phone1' : IDL.Text,
    'phone2' : IDL.Text,
    'phone3' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : RecordId,
    'inquiryType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  const CounselingBooking = IDL.Record({
    'id' : RecordId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'countryInterests' : IDL.Vec(IDL.Text),
    'preferredTime' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
    'educationLevel' : IDL.Text,
  });
  const FAQ = IDL.Record({
    'id' : RecordId,
    'question' : IDL.Text,
    'order' : IDL.Nat,
    'answer' : IDL.Text,
  });
  const CountryUniversity = IDL.Record({
    'id' : RecordId,
    'name' : IDL.Text,
    'tuition' : IDL.Text,
    'website' : IDL.Text,
    'logoUrl' : IDL.Text,
    'ranking' : IDL.Text,
  });
  const VisaStep = IDL.Record({
    'id' : RecordId,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
  });
  const CostBreakdown = IDL.Record({
    'miscellaneous' : IDL.Text,
    'food' : IDL.Text,
    'transport' : IDL.Text,
    'totalMonthly' : IDL.Text,
    'accommodation' : IDL.Text,
  });
  const CountryDetailContent = IDL.Record({
    'heroImageUrl' : IDL.Text,
    'workRights' : IDL.Text,
    'faqs' : IDL.Vec(FAQ),
    'universities' : IDL.Vec(CountryUniversity),
    'heroSubtitle' : IDL.Text,
    'visaProcess' : IDL.Vec(VisaStep),
    'countrySlug' : IDL.Text,
    'prOpportunities' : IDL.Text,
    'popularCourses' : IDL.Vec(IDL.Text),
    'costOfLiving' : CostBreakdown,
    'heroTitle' : IDL.Text,
    'scholarships' : IDL.Vec(IDL.Text),
    'whyStudyHere' : IDL.Text,
  });
  const DemoClassBooking = IDL.Record({
    'id' : RecordId,
    'name' : IDL.Text,
    'testType' : IDL.Text,
    'email' : IDL.Text,
    'preferredTime' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  const EventItem = IDL.Record({
    'id' : RecordId,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'registrationLink' : IDL.Text,
    'location' : IDL.Text,
  });
  const FacebookReviewsBadge = IDL.Record({
    'reviewUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
    'rating' : IDL.Text,
    'reviewCount' : IDL.Text,
  });
  const FooterLink = IDL.Record({ 'url' : IDL.Text, 'linkLabel' : IDL.Text });
  const FooterSocialLink = IDL.Record({
    'url' : IDL.Text,
    'platform' : IDL.Text,
  });
  const GoogleReviewsBadge = IDL.Record({
    'reviewUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
    'rating' : IDL.Text,
    'reviewCount' : IDL.Text,
  });
  const EduLoanPartner = IDL.Record({
    'id' : IDL.Text,
    'websiteUrl' : IDL.Text,
    'name' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const OfficeLocation = IDL.Record({
    'id' : IDL.Text,
    'city' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FooterContent = IDL.Record({
    'facebookReviewsBadge' : FacebookReviewsBadge,
    'serviceLinks' : IDL.Vec(FooterLink),
    'socialLinks' : IDL.Vec(FooterSocialLink),
    'googleReviewsBadge' : GoogleReviewsBadge,
    'copyrightText' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'quickLinks' : IDL.Vec(FooterLink),
    'countryLinks' : IDL.Vec(FooterLink),
    'eduLoanPartners' : IDL.Vec(EduLoanPartner),
    'officeLocations' : IDL.Vec(OfficeLocation),
  });
  const FreeCounselingBenefitPoint = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const FreeCounselingContent = IDL.Record({
    'heroImageUrl' : IDL.Text,
    'formDescription' : IDL.Text,
    'benefitPoints' : IDL.Vec(FreeCounselingBenefitPoint),
    'ctaText' : IDL.Text,
    'heroSubheadline' : IDL.Text,
    'heroHeadline' : IDL.Text,
  });
  const GalleryEntry = IDL.Record({
    'id' : IDL.Nat,
    'studentName' : IDL.Text,
    'order' : IDL.Nat,
    'universityAdmitted' : IDL.Text,
    'createdAt' : IDL.Int,
    'imageUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
    'destinationCountry' : IDL.Text,
    'visaStatus' : IDL.Text,
  });
  const HeroContent = IDL.Record({
    'yearsExperience' : IDL.Text,
    'headline' : IDL.Text,
    'studentsGuided' : IDL.Text,
    'subheadline' : IDL.Text,
    'universityPartnerships' : IDL.Text,
    'visaSuccessRate' : IDL.Text,
  });
  const HomeSocialLink = IDL.Record({
    'url' : IDL.Text,
    'platform' : IDL.Text,
  });
  const HomeSectionPoint = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const HomeSectionsContent = IDL.Record({
    'universityMarqueeEnabled' : IDL.Bool,
    'whyChooseUsHeadline' : IDL.Text,
    'ctaBannerSubheadline' : IDL.Text,
    'footerSocialLinks' : IDL.Vec(HomeSocialLink),
    'whyChooseUsPoints' : IDL.Vec(HomeSectionPoint),
    'ctaBannerButtonText' : IDL.Text,
    'footerDescription' : IDL.Text,
    'ctaBannerHeadline' : IDL.Text,
    'eventsDisplayCount' : IDL.Nat,
    'testimonialsDisplayCount' : IDL.Nat,
  });
  const ImmigrationConsultation = IDL.Record({
    'id' : RecordId,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'visaType' : IDL.Text,
    'preferredTime' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  const ImmigrationVisa = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'successRate' : IDL.Text,
    'description' : IDL.Text,
    'processingTime' : IDL.Text,
    'visaType' : IDL.Text,
    'imageUrl' : IDL.Text,
    'documentsRequired' : IDL.Vec(IDL.Text),
    'requirements' : IDL.Vec(IDL.Text),
    'eligibilityCriteria' : IDL.Vec(IDL.Text),
  });
  const JobApplication = IDL.Record({
    'id' : IDL.Nat,
    'applicantName' : IDL.Text,
    'positionApplied' : IDL.Text,
    'submittedAt' : IDL.Int,
    'coverLetter' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'jobOpeningId' : IDL.Nat,
    'resumeUrl' : IDL.Text,
  });
  const LeadershipMember = IDL.Record({
    'id' : RecordId,
    'bio' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const LifeAtValmikiGalleryImage = IDL.Record({
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
  });
  const LifeAtValmikiPerk = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const LifeAtValmikiContent = IDL.Record({
    'heroImageUrl' : IDL.Text,
    'galleryImages' : IDL.Vec(LifeAtValmikiGalleryImage),
    'missionText' : IDL.Text,
    'heroSubheadline' : IDL.Text,
    'cultureDescription' : IDL.Text,
    'perks' : IDL.Vec(LifeAtValmikiPerk),
    'heroHeadline' : IDL.Text,
  });
  const NewsletterSubscription = IDL.Record({
    'id' : RecordId,
    'email' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const PageHeroContent = IDL.Record({
    'headline' : IDL.Text,
    'imageUrl' : IDL.Text,
    'subheadline' : IDL.Text,
    'pageId' : IDL.Text,
  });
  const BeOurPartnerInquiry = IDL.Record({
    'id' : IDL.Nat,
    'contactName' : IDL.Text,
    'partnershipType' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ServiceFAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const ServiceProcessStep = IDL.Record({
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const ServiceDetailContent = IDL.Record({
    'faqs' : IDL.Vec(ServiceFAQ),
    'ctaButtonText' : IDL.Text,
    'overview' : IDL.Text,
    'processSteps' : IDL.Vec(ServiceProcessStep),
    'heroImage' : IDL.Text,
    'ctaText' : IDL.Text,
    'heroSubheadline' : IDL.Text,
    'serviceId' : IDL.Text,
    'heroHeadline' : IDL.Text,
    'eligibilityCriteria' : IDL.Vec(IDL.Text),
    'whyChooseValmiki' : IDL.Vec(IDL.Text),
    'whatIsIncluded' : IDL.Vec(IDL.Text),
  });
  const ServiceItem = IDL.Record({
    'id' : RecordId,
    'features' : IDL.Vec(IDL.Text),
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'ctaLink' : IDL.Text,
  });
  const ProcessStep = IDL.Record({
    'id' : RecordId,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const ScholarshipInfo = IDL.Record({
    'id' : RecordId,
    'name' : IDL.Text,
    'deadline' : IDL.Text,
    'eligibility' : IDL.Text,
    'amount' : IDL.Text,
  });
  const StudyAbroadContent = IDL.Record({
    'headline' : IDL.Text,
    'intakeInfo' : IDL.Text,
    'processSteps' : IDL.Vec(ProcessStep),
    'imageUrl' : IDL.Text,
    'introduction' : IDL.Text,
    'scholarships' : IDL.Vec(ScholarshipInfo),
  });
  const TeamMember = IDL.Record({
    'id' : RecordId,
    'bio' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const BatchTiming = IDL.Record({
    'id' : RecordId,
    'endDate' : IDL.Text,
    'enrolled' : IDL.Nat,
    'capacity' : IDL.Nat,
    'schedule' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const TestPrepExam = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Text,
    'scoreRange' : IDL.Text,
    'cost' : IDL.Text,
    'successRate' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'batchTimings' : IDL.Vec(BatchTiming),
  });
  const TestimonialItem = IDL.Record({
    'id' : RecordId,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'text' : IDL.Text,
    'university' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
    'rating' : IDL.Nat,
    'course' : IDL.Text,
    'youtubeUrl' : IDL.Opt(IDL.Text),
  });
  const VisaEligibilityResult = IDL.Record({
    'id' : RecordId,
    'age' : IDL.Nat,
    'country' : IDL.Text,
    'education' : IDL.Text,
    'testScores' : IDL.Text,
    'visaType' : IDL.Text,
    'timestamp' : Timestamp,
    'workExperienceYears' : IDL.Nat,
    'resultPercentage' : IDL.Nat,
  });
  const WebsiteTheme = IDL.Record({
    'backgroundColor' : IDL.Text,
    'primaryColor' : IDL.Text,
    'buttonTextColor' : IDL.Text,
    'accentColor' : IDL.Text,
    'buttonColor' : IDL.Text,
    'secondaryColor' : IDL.Text,
    'footerBgColor' : IDL.Text,
    'footerTextColor' : IDL.Text,
    'headingTextColor' : IDL.Text,
    'bodyTextColor' : IDL.Text,
  });
  const SubmissionResult = IDL.Record({
    'id' : RecordId,
    'timestamp' : Timestamp,
  });
  const JobApplicationInput = IDL.Record({
    'applicantName' : IDL.Text,
    'positionApplied' : IDL.Text,
    'coverLetter' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'jobOpeningId' : IDL.Nat,
    'resumeUrl' : IDL.Text,
  });
  const BeOurPartnerInquiryInput = IDL.Record({
    'contactName' : IDL.Text,
    'partnershipType' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addBatchTiming' : IDL.Func(
        [
          SessionToken,
          IDL.Text,
          IDL.Record({
            'endDate' : IDL.Text,
            'enrolled' : IDL.Nat,
            'capacity' : IDL.Nat,
            'schedule' : IDL.Text,
            'startDate' : IDL.Text,
          }),
        ],
        [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
        [],
      ),
    'addBlogPost' : IDL.Func(
        [SessionToken, BlogPostInput],
        [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
        [],
      ),
    'addCountry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addEvent' : IDL.Func(
        [IDL.Text, EventItemInput],
        [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
        [],
      ),
    'addGalleryEntry' : IDL.Func(
        [SessionToken, GalleryEntryInput],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'addJobOpening' : IDL.Func(
        [SessionToken, JobOpeningInput],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'addPartnerUniversity' : IDL.Func(
        [SessionToken, PartnerUniversity],
        [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
        [],
      ),
    'addService' : IDL.Func(
        [IDL.Text, ServiceItemInput],
        [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
        [],
      ),
    'addTeamMember' : IDL.Func(
        [IDL.Text, TeamMemberInput],
        [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, TestimonialInput],
        [IDL.Variant({ 'ok' : RecordId, 'err' : IDL.Text })],
        [],
      ),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : SessionToken, 'err' : IDL.Text })],
        [],
      ),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'deleteBatchTiming' : IDL.Func(
        [SessionToken, IDL.Text, RecordId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteBlogPost' : IDL.Func(
        [SessionToken, RecordId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteCountry' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteEvent' : IDL.Func(
        [IDL.Text, RecordId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteGalleryEntry' : IDL.Func(
        [SessionToken, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteJobApplication' : IDL.Func(
        [SessionToken, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteJobOpening' : IDL.Func(
        [SessionToken, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deletePartnerUniversity' : IDL.Func(
        [SessionToken, RecordId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteService' : IDL.Func(
        [IDL.Text, RecordId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteTeamMember' : IDL.Func(
        [IDL.Text, RecordId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteTestimonial' : IDL.Func(
        [IDL.Text, RecordId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAboutPageContent' : IDL.Func([], [AboutPageContent], ['query']),
    'getActiveJobOpenings' : IDL.Func([], [IDL.Vec(JobOpening)], ['query']),
    'getAdminDashboardStats' : IDL.Func([], [AdminDashboardStats], ['query']),
    'getAllCountries' : IDL.Func([], [IDL.Vec(CountryInfo)], ['query']),
    'getAllPageContents' : IDL.Func([], [IDL.Vec(PageContent)], ['query']),
    'getBeOurPartnerContent' : IDL.Func(
        [],
        [IDL.Opt(BeOurPartnerContent)],
        ['query'],
      ),
    'getBlogPostById' : IDL.Func([RecordId], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getCounselingBookings' : IDL.Func(
        [],
        [IDL.Vec(CounselingBooking)],
        ['query'],
      ),
    'getCountryDetail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CountryDetailContent)],
        ['query'],
      ),
    'getCountryDetailAll' : IDL.Func(
        [],
        [IDL.Vec(CountryDetailContent)],
        ['query'],
      ),
    'getCountryDetailBySlug' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CountryDetailContent)],
        ['query'],
      ),
    'getCountryInfo' : IDL.Func([IDL.Text], [IDL.Opt(CountryInfo)], ['query']),
    'getCountryInfoAll' : IDL.Func([], [IDL.Vec(CountryInfo)], ['query']),
    'getDemoClassBookings' : IDL.Func(
        [],
        [IDL.Vec(DemoClassBooking)],
        ['query'],
      ),
    'getEvents' : IDL.Func([], [IDL.Vec(EventItem)], ['query']),
    'getFooterContent' : IDL.Func([], [FooterContent], ['query']),
    'getFreeCounselingContent' : IDL.Func(
        [],
        [FreeCounselingContent],
        ['query'],
      ),
    'getGalleryEntries' : IDL.Func([], [IDL.Vec(GalleryEntry)], ['query']),
    'getHeroContent' : IDL.Func([], [HeroContent], ['query']),
    'getHomeSectionsContent' : IDL.Func([], [HomeSectionsContent], ['query']),
    'getImmigrationConsultations' : IDL.Func(
        [],
        [IDL.Vec(ImmigrationConsultation)],
        ['query'],
      ),
    'getImmigrationVisaById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ImmigrationVisa)],
        ['query'],
      ),
    'getImmigrationVisas' : IDL.Func([], [IDL.Vec(ImmigrationVisa)], ['query']),
    'getJobApplications' : IDL.Func(
        [SessionToken],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getJobOpenings' : IDL.Func([], [IDL.Vec(JobOpening)], ['query']),
    'getLeadershipMembers' : IDL.Func(
        [],
        [IDL.Vec(LeadershipMember)],
        ['query'],
      ),
    'getLifeAtValmikiContent' : IDL.Func([], [LifeAtValmikiContent], ['query']),
    'getNewsletterSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSubscription)],
        ['query'],
      ),
    'getPageContent' : IDL.Func([IDL.Text], [IDL.Opt(PageContent)], ['query']),
    'getPageHeroContent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PageHeroContent)],
        ['query'],
      ),
    'getPartnerInquiries' : IDL.Func(
        [SessionToken],
        [IDL.Vec(BeOurPartnerInquiry)],
        ['query'],
      ),
    'getPartnerUniversities' : IDL.Func(
        [],
        [IDL.Vec(PartnerUniversity)],
        ['query'],
      ),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getServiceDetail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ServiceDetailContent)],
        ['query'],
      ),
    'getServices' : IDL.Func([], [IDL.Vec(ServiceItem)], ['query']),
    'getStudyAbroadContent' : IDL.Func([], [StudyAbroadContent], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getTestPrepExamById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TestPrepExam)],
        ['query'],
      ),
    'getTestPrepExams' : IDL.Func([], [IDL.Vec(TestPrepExam)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(TestimonialItem)], ['query']),
    'getVisaEligibilityResults' : IDL.Func(
        [],
        [IDL.Vec(VisaEligibilityResult)],
        ['query'],
      ),
    'getVisibleGalleryEntries' : IDL.Func(
        [],
        [IDL.Vec(GalleryEntry)],
        ['query'],
      ),
    'getWebsiteTheme' : IDL.Func([], [WebsiteTheme], ['query']),
    'reorderCountries' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'reorderPartnerUniversities' : IDL.Func(
        [SessionToken, IDL.Vec(RecordId)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setBeOurPartnerContent' : IDL.Func(
        [SessionToken, BeOurPartnerContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setServiceDetail' : IDL.Func(
        [SessionToken, ServiceDetailContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SubmissionResult],
        [],
      ),
    'submitCounselingBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [SubmissionResult],
        [],
      ),
    'submitDemoClassBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SubmissionResult],
        [],
      ),
    'submitImmigrationConsultation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SubmissionResult],
        [],
      ),
    'submitJobApplication' : IDL.Func(
        [JobApplicationInput],
        [JobApplication],
        [],
      ),
    'submitPartnerInquiry' : IDL.Func(
        [BeOurPartnerInquiryInput],
        [SubmissionResult],
        [],
      ),
    'submitVisaEligibility' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [SubmissionResult],
        [],
      ),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [SubmissionResult], []),
    'toggleBlogPostPublish' : IDL.Func(
        [SessionToken, RecordId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'toggleGalleryEntryVisibility' : IDL.Func(
        [SessionToken, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateAboutPageContent' : IDL.Func(
        [SessionToken, AboutPageContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateBatchTiming' : IDL.Func(
        [
          SessionToken,
          IDL.Text,
          RecordId,
          IDL.Record({
            'endDate' : IDL.Text,
            'enrolled' : IDL.Nat,
            'capacity' : IDL.Nat,
            'schedule' : IDL.Text,
            'startDate' : IDL.Text,
          }),
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateBlogPost' : IDL.Func(
        [SessionToken, RecordId, BlogPostInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateContactInfo' : IDL.Func(
        [IDL.Text, ContactInfo],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCountryDetailBySlug' : IDL.Func(
        [SessionToken, CountryDetailContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCountryInfo' : IDL.Func(
        [IDL.Text, CountryInfo],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateEvent' : IDL.Func(
        [IDL.Text, RecordId, EventItemInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateFooterContent' : IDL.Func(
        [IDL.Text, FooterContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateFreeCounselingContent' : IDL.Func(
        [IDL.Text, FreeCounselingContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateGalleryEntry' : IDL.Func(
        [SessionToken, IDL.Nat, GalleryEntryInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateHeroContent' : IDL.Func(
        [IDL.Text, HeroContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateHomeSectionsContent' : IDL.Func(
        [IDL.Text, HomeSectionsContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateImmigrationVisa' : IDL.Func(
        [SessionToken, ImmigrationVisa],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateJobOpening' : IDL.Func(
        [SessionToken, IDL.Nat, JobOpeningInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateLeadershipMembers' : IDL.Func(
        [SessionToken, IDL.Vec(LeadershipMember)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateLifeAtValmikiContent' : IDL.Func(
        [IDL.Text, LifeAtValmikiContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updatePageContent' : IDL.Func(
        [SessionToken, IDL.Text, PageContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updatePageHeroContent' : IDL.Func(
        [IDL.Text, PageHeroContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updatePartnerUniversity' : IDL.Func(
        [SessionToken, RecordId, PartnerUniversity],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateService' : IDL.Func(
        [IDL.Text, RecordId, ServiceItemInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateStudyAbroadContent' : IDL.Func(
        [SessionToken, StudyAbroadContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateTeamMember' : IDL.Func(
        [IDL.Text, RecordId, TeamMemberInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateTestPrepExam' : IDL.Func(
        [SessionToken, TestPrepExam],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateTestimonial' : IDL.Func(
        [IDL.Text, RecordId, TestimonialInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateWebsiteTheme' : IDL.Func(
        [IDL.Text, WebsiteTheme],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'verifyAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };