/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutPageContent {
  'mission' : string,
  'companyStory' : string,
  'imageUrl' : string,
  'achievements' : Array<Achievement>,
  'vision' : string,
  'timeline' : Array<TimelineEntry>,
}
export interface Achievement {
  'id' : RecordId,
  'metric' : string,
  'icon' : string,
  'description' : string,
}
export interface AdminDashboardStats {
  'pending' : bigint,
  'totalLeads' : bigint,
  'thisMonth' : bigint,
}
export interface BatchTiming {
  'id' : RecordId,
  'endDate' : string,
  'enrolled' : bigint,
  'capacity' : bigint,
  'schedule' : string,
  'startDate' : string,
}
export interface BeOurPartnerContent {
  'formDescription' : string,
  'partnershipTypes' : Array<PartnershipTypeItem>,
  'generalBenefits' : Array<string>,
  'heroImage' : string,
  'heroSubheadline' : string,
  'heroHeadline' : string,
}
export interface BeOurPartnerInquiry {
  'id' : bigint,
  'contactName' : string,
  'partnershipType' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'companyName' : string,
  'phone' : string,
}
export interface BeOurPartnerInquiryInput {
  'contactName' : string,
  'partnershipType' : string,
  'email' : string,
  'message' : string,
  'companyName' : string,
  'phone' : string,
}
export interface BlogPost {
  'id' : RecordId,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : Timestamp,
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : bigint,
  'updatedAt' : Timestamp,
  'featuredImageUrl' : string,
  'category' : string,
}
export interface BlogPostInput {
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'slug' : string,
  'featuredImageUrl' : string,
  'category' : string,
}
export interface ContactInfo {
  'branch2Name' : string,
  'email' : string,
  'branch1Name' : string,
  'branch3Name' : string,
  'address1' : string,
  'address2' : string,
  'address3' : string,
  'phone1' : string,
  'phone2' : string,
  'phone3' : string,
}
export interface ContactSubmission {
  'id' : RecordId,
  'inquiryType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export interface CostBreakdown {
  'miscellaneous' : string,
  'food' : string,
  'transport' : string,
  'totalMonthly' : string,
  'accommodation' : string,
}
export interface CounselingBooking {
  'id' : RecordId,
  'name' : string,
  'email' : string,
  'countryInterests' : Array<string>,
  'preferredTime' : string,
  'timestamp' : Timestamp,
  'phone' : string,
  'educationLevel' : string,
}
export interface CountryDetailContent {
  'heroImageUrl' : string,
  'workRights' : string,
  'faqs' : Array<FAQ>,
  'universities' : Array<CountryUniversity>,
  'heroSubtitle' : string,
  'visaProcess' : Array<VisaStep>,
  'countrySlug' : string,
  'prOpportunities' : string,
  'popularCourses' : Array<string>,
  'costOfLiving' : CostBreakdown,
  'heroTitle' : string,
  'scholarships' : Array<string>,
  'whyStudyHere' : string,
}
export interface CountryFAQ { 'question' : string, 'answer' : string }
export interface CountryInfo {
  'order' : bigint,
  'acceptanceRate' : string,
  'visaSteps' : Array<string>,
  'faqs' : Array<CountryFAQ>,
  'slug' : string,
  'description' : string,
  'tuition' : string,
  'averageCost' : string,
  'flagImage' : string,
  'processingTime' : string,
  'heroImage' : string,
  'popularCourses' : Array<string>,
  'topUniversities' : Array<CountryTopUniversity>,
  'workOpportunities' : string,
  'prPathway' : string,
  'intakeMonths' : string,
  'requirements' : Array<string>,
  'scholarships' : Array<string>,
  'visaSuccessRate' : string,
}
export interface CountryTopUniversity { 'name' : string, 'ranking' : string }
export interface CountryUniversity {
  'id' : RecordId,
  'name' : string,
  'tuition' : string,
  'website' : string,
  'logoUrl' : string,
  'ranking' : string,
}
export interface DemoClassBooking {
  'id' : RecordId,
  'name' : string,
  'testType' : string,
  'email' : string,
  'preferredTime' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export interface EduLoanPartner {
  'id' : string,
  'websiteUrl' : string,
  'name' : string,
  'logoUrl' : string,
}
export interface EventItem {
  'id' : RecordId,
  'title' : string,
  'date' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'registrationLink' : string,
  'location' : string,
}
export interface EventItemInput {
  'title' : string,
  'date' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'registrationLink' : string,
  'location' : string,
}
export interface FAQ {
  'id' : RecordId,
  'question' : string,
  'order' : bigint,
  'answer' : string,
}
export interface FacebookReviewsBadge {
  'reviewUrl' : string,
  'isVisible' : boolean,
  'rating' : string,
  'reviewCount' : string,
}
export interface FooterContent {
  'facebookReviewsBadge' : FacebookReviewsBadge,
  'serviceLinks' : Array<FooterLink>,
  'socialLinks' : Array<FooterSocialLink>,
  'googleReviewsBadge' : GoogleReviewsBadge,
  'copyrightText' : string,
  'whatsappNumber' : string,
  'quickLinks' : Array<FooterLink>,
  'countryLinks' : Array<FooterLink>,
  'eduLoanPartners' : Array<EduLoanPartner>,
  'officeLocations' : Array<OfficeLocation>,
}
export interface FooterLink { 'url' : string, 'linkLabel' : string }
export interface FooterSocialLink { 'url' : string, 'platform' : string }
export interface FreeCounselingBenefitPoint {
  'title' : string,
  'description' : string,
}
export interface FreeCounselingContent {
  'heroImageUrl' : string,
  'formDescription' : string,
  'benefitPoints' : Array<FreeCounselingBenefitPoint>,
  'ctaText' : string,
  'heroSubheadline' : string,
  'heroHeadline' : string,
}
export interface GalleryEntry {
  'id' : bigint,
  'studentName' : string,
  'order' : bigint,
  'universityAdmitted' : string,
  'createdAt' : bigint,
  'imageUrl' : string,
  'isVisible' : boolean,
  'destinationCountry' : string,
  'visaStatus' : string,
}
export interface GalleryEntryInput {
  'studentName' : string,
  'order' : bigint,
  'universityAdmitted' : string,
  'imageUrl' : string,
  'isVisible' : boolean,
  'destinationCountry' : string,
  'visaStatus' : string,
}
export interface GoogleReviewsBadge {
  'reviewUrl' : string,
  'isVisible' : boolean,
  'rating' : string,
  'reviewCount' : string,
}
export interface HeroContent {
  'yearsExperience' : string,
  'headline' : string,
  'studentsGuided' : string,
  'subheadline' : string,
  'universityPartnerships' : string,
  'visaSuccessRate' : string,
}
export interface HomeSectionPoint {
  'title' : string,
  'icon' : string,
  'description' : string,
}
export interface HomeSectionsContent {
  'universityMarqueeEnabled' : boolean,
  'whyChooseUsHeadline' : string,
  'ctaBannerSubheadline' : string,
  'footerSocialLinks' : Array<HomeSocialLink>,
  'whyChooseUsPoints' : Array<HomeSectionPoint>,
  'ctaBannerButtonText' : string,
  'footerDescription' : string,
  'ctaBannerHeadline' : string,
  'eventsDisplayCount' : bigint,
  'testimonialsDisplayCount' : bigint,
}
export interface HomeSocialLink { 'url' : string, 'platform' : string }
export interface ImmigrationConsultation {
  'id' : RecordId,
  'country' : string,
  'name' : string,
  'email' : string,
  'visaType' : string,
  'preferredTime' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export interface ImmigrationVisa {
  'id' : string,
  'title' : string,
  'successRate' : string,
  'description' : string,
  'processingTime' : string,
  'visaType' : string,
  'imageUrl' : string,
  'documentsRequired' : Array<string>,
  'requirements' : Array<string>,
  'eligibilityCriteria' : Array<string>,
}
export interface JobApplication {
  'id' : bigint,
  'applicantName' : string,
  'positionApplied' : string,
  'submittedAt' : bigint,
  'coverLetter' : string,
  'email' : string,
  'phone' : string,
  'jobOpeningId' : bigint,
  'resumeUrl' : string,
}
export interface JobApplicationInput {
  'applicantName' : string,
  'positionApplied' : string,
  'coverLetter' : string,
  'email' : string,
  'phone' : string,
  'jobOpeningId' : bigint,
  'resumeUrl' : string,
}
export interface JobOpening {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'department' : string,
  'requirements' : string,
  'location' : string,
}
export interface JobOpeningInput {
  'title' : string,
  'description' : string,
  'isActive' : boolean,
  'department' : string,
  'requirements' : string,
  'location' : string,
}
export interface LeadershipMember {
  'id' : RecordId,
  'bio' : string,
  'order' : bigint,
  'name' : string,
  'role' : string,
  'imageUrl' : string,
}
export interface LifeAtValmikiContent {
  'heroImageUrl' : string,
  'galleryImages' : Array<LifeAtValmikiGalleryImage>,
  'missionText' : string,
  'heroSubheadline' : string,
  'cultureDescription' : string,
  'perks' : Array<LifeAtValmikiPerk>,
  'heroHeadline' : string,
}
export interface LifeAtValmikiGalleryImage {
  'imageUrl' : string,
  'caption' : string,
}
export interface LifeAtValmikiPerk {
  'title' : string,
  'icon' : string,
  'description' : string,
}
export interface NewsletterSubscription {
  'id' : RecordId,
  'email' : string,
  'timestamp' : Timestamp,
}
export interface OfficeLocation {
  'id' : string,
  'city' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface PageContent {
  'heroImageUrl' : string,
  'metaDescription' : string,
  'bodyContent' : string,
  'title' : string,
  'isActive' : boolean,
  'heroSubheadline' : string,
  'sections' : Array<PageSection>,
  'heroHeadline' : string,
  'pageId' : string,
}
export interface PageHeroContent {
  'headline' : string,
  'imageUrl' : string,
  'subheadline' : string,
  'pageId' : string,
}
export interface PageSection {
  'id' : string,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'sectionType' : string,
  'imageUrl' : string,
  'items' : Array<string>,
}
export interface PartnerUniversity {
  'id' : RecordId,
  'country' : string,
  'order' : bigint,
  'name' : string,
  'website' : string,
  'logoUrl' : string,
}
export interface PartnershipTypeItem {
  'title' : string,
  'icon' : string,
  'description' : string,
  'benefits' : Array<string>,
}
export interface ProcessStep {
  'id' : RecordId,
  'title' : string,
  'order' : bigint,
  'icon' : string,
  'description' : string,
}
export type RecordId = bigint;
export interface ScholarshipInfo {
  'id' : RecordId,
  'name' : string,
  'deadline' : string,
  'eligibility' : string,
  'amount' : string,
}
export interface ServiceDetailContent {
  'faqs' : Array<ServiceFAQ>,
  'ctaButtonText' : string,
  'overview' : string,
  'processSteps' : Array<ServiceProcessStep>,
  'heroImage' : string,
  'ctaText' : string,
  'heroSubheadline' : string,
  'serviceId' : string,
  'heroHeadline' : string,
  'eligibilityCriteria' : Array<string>,
  'whyChooseValmiki' : Array<string>,
  'whatIsIncluded' : Array<string>,
}
export interface ServiceFAQ { 'question' : string, 'answer' : string }
export interface ServiceItem {
  'id' : RecordId,
  'features' : Array<string>,
  'order' : bigint,
  'icon' : string,
  'name' : string,
  'description' : string,
  'ctaLink' : string,
}
export interface ServiceItemInput {
  'features' : Array<string>,
  'order' : bigint,
  'icon' : string,
  'name' : string,
  'description' : string,
  'ctaLink' : string,
}
export interface ServiceProcessStep {
  'title' : string,
  'order' : bigint,
  'icon' : string,
  'description' : string,
}
export type SessionToken = string;
export interface StudyAbroadContent {
  'headline' : string,
  'intakeInfo' : string,
  'processSteps' : Array<ProcessStep>,
  'imageUrl' : string,
  'introduction' : string,
  'scholarships' : Array<ScholarshipInfo>,
}
export interface SubmissionResult { 'id' : RecordId, 'timestamp' : Timestamp }
export interface TeamMember {
  'id' : RecordId,
  'bio' : string,
  'order' : bigint,
  'name' : string,
  'role' : string,
  'imageUrl' : string,
}
export interface TeamMemberInput {
  'bio' : string,
  'order' : bigint,
  'name' : string,
  'role' : string,
  'imageUrl' : string,
}
export interface TestPrepExam {
  'id' : string,
  'duration' : string,
  'scoreRange' : string,
  'cost' : string,
  'successRate' : string,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'batchTimings' : Array<BatchTiming>,
}
export interface TestimonialInput {
  'country' : string,
  'name' : string,
  'text' : string,
  'university' : string,
  'imageUrl' : string,
  'isVisible' : boolean,
  'rating' : bigint,
  'course' : string,
  'youtubeUrl' : [] | [string],
}
export interface TestimonialItem {
  'id' : RecordId,
  'country' : string,
  'name' : string,
  'text' : string,
  'university' : string,
  'imageUrl' : string,
  'isVisible' : boolean,
  'rating' : bigint,
  'course' : string,
  'youtubeUrl' : [] | [string],
}
export interface TimelineEntry {
  'id' : RecordId,
  'year' : string,
  'description' : string,
  'milestone' : string,
}
export type Timestamp = bigint;
export interface VisaEligibilityResult {
  'id' : RecordId,
  'age' : bigint,
  'country' : string,
  'education' : string,
  'testScores' : string,
  'visaType' : string,
  'timestamp' : Timestamp,
  'workExperienceYears' : bigint,
  'resultPercentage' : bigint,
}
export interface VisaStep {
  'id' : RecordId,
  'title' : string,
  'order' : bigint,
  'description' : string,
}
export interface WebsiteTheme {
  'backgroundColor' : string,
  'primaryColor' : string,
  'buttonTextColor' : string,
  'accentColor' : string,
  'buttonColor' : string,
  'secondaryColor' : string,
  'footerBgColor' : string,
  'footerTextColor' : string,
  'headingTextColor' : string,
  'bodyTextColor' : string,
}
export interface _SERVICE {
  'addBatchTiming' : ActorMethod<
    [
      SessionToken,
      string,
      {
        'endDate' : string,
        'enrolled' : bigint,
        'capacity' : bigint,
        'schedule' : string,
        'startDate' : string,
      },
    ],
    { 'ok' : RecordId } |
      { 'err' : string }
  >,
  'addBlogPost' : ActorMethod<
    [SessionToken, BlogPostInput],
    { 'ok' : RecordId } |
      { 'err' : string }
  >,
  'addCountry' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addEvent' : ActorMethod<
    [string, EventItemInput],
    { 'ok' : RecordId } |
      { 'err' : string }
  >,
  'addGalleryEntry' : ActorMethod<
    [SessionToken, GalleryEntryInput],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'addJobOpening' : ActorMethod<
    [SessionToken, JobOpeningInput],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'addPartnerUniversity' : ActorMethod<
    [SessionToken, PartnerUniversity],
    { 'ok' : RecordId } |
      { 'err' : string }
  >,
  'addService' : ActorMethod<
    [string, ServiceItemInput],
    { 'ok' : RecordId } |
      { 'err' : string }
  >,
  'addTeamMember' : ActorMethod<
    [string, TeamMemberInput],
    { 'ok' : RecordId } |
      { 'err' : string }
  >,
  'addTestimonial' : ActorMethod<
    [string, TestimonialInput],
    { 'ok' : RecordId } |
      { 'err' : string }
  >,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : SessionToken } |
      { 'err' : string }
  >,
  'adminLogout' : ActorMethod<[string], undefined>,
  'deleteBatchTiming' : ActorMethod<
    [SessionToken, string, RecordId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteBlogPost' : ActorMethod<
    [SessionToken, RecordId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteCountry' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteEvent' : ActorMethod<
    [string, RecordId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteGalleryEntry' : ActorMethod<
    [SessionToken, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteJobApplication' : ActorMethod<
    [SessionToken, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteJobOpening' : ActorMethod<
    [SessionToken, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deletePartnerUniversity' : ActorMethod<
    [SessionToken, RecordId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteService' : ActorMethod<
    [string, RecordId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteTeamMember' : ActorMethod<
    [string, RecordId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteTestimonial' : ActorMethod<
    [string, RecordId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAboutPageContent' : ActorMethod<[], AboutPageContent>,
  'getActiveJobOpenings' : ActorMethod<[], Array<JobOpening>>,
  'getAdminDashboardStats' : ActorMethod<[], AdminDashboardStats>,
  'getAllCountries' : ActorMethod<[], Array<CountryInfo>>,
  'getAllPageContents' : ActorMethod<[], Array<PageContent>>,
  'getBeOurPartnerContent' : ActorMethod<[], [] | [BeOurPartnerContent]>,
  'getBlogPostById' : ActorMethod<[RecordId], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getCounselingBookings' : ActorMethod<[], Array<CounselingBooking>>,
  'getCountryDetail' : ActorMethod<[string], [] | [CountryDetailContent]>,
  'getCountryDetailAll' : ActorMethod<[], Array<CountryDetailContent>>,
  'getCountryDetailBySlug' : ActorMethod<[string], [] | [CountryDetailContent]>,
  'getCountryInfo' : ActorMethod<[string], [] | [CountryInfo]>,
  'getCountryInfoAll' : ActorMethod<[], Array<CountryInfo>>,
  'getDemoClassBookings' : ActorMethod<[], Array<DemoClassBooking>>,
  'getEvents' : ActorMethod<[], Array<EventItem>>,
  'getFooterContent' : ActorMethod<[], FooterContent>,
  'getFreeCounselingContent' : ActorMethod<[], FreeCounselingContent>,
  'getGalleryEntries' : ActorMethod<[], Array<GalleryEntry>>,
  'getHeroContent' : ActorMethod<[], HeroContent>,
  'getHomeSectionsContent' : ActorMethod<[], HomeSectionsContent>,
  'getImmigrationConsultations' : ActorMethod<
    [],
    Array<ImmigrationConsultation>
  >,
  'getImmigrationVisaById' : ActorMethod<[string], [] | [ImmigrationVisa]>,
  'getImmigrationVisas' : ActorMethod<[], Array<ImmigrationVisa>>,
  'getJobApplications' : ActorMethod<[SessionToken], Array<JobApplication>>,
  'getJobOpenings' : ActorMethod<[], Array<JobOpening>>,
  'getLeadershipMembers' : ActorMethod<[], Array<LeadershipMember>>,
  'getLifeAtValmikiContent' : ActorMethod<[], LifeAtValmikiContent>,
  'getNewsletterSubscriptions' : ActorMethod<[], Array<NewsletterSubscription>>,
  'getPageContent' : ActorMethod<[string], [] | [PageContent]>,
  'getPageHeroContent' : ActorMethod<[string], [] | [PageHeroContent]>,
  'getPartnerInquiries' : ActorMethod<
    [SessionToken],
    Array<BeOurPartnerInquiry>
  >,
  'getPartnerUniversities' : ActorMethod<[], Array<PartnerUniversity>>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getServiceDetail' : ActorMethod<[string], [] | [ServiceDetailContent]>,
  'getServices' : ActorMethod<[], Array<ServiceItem>>,
  'getStudyAbroadContent' : ActorMethod<[], StudyAbroadContent>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getTestPrepExamById' : ActorMethod<[string], [] | [TestPrepExam]>,
  'getTestPrepExams' : ActorMethod<[], Array<TestPrepExam>>,
  'getTestimonials' : ActorMethod<[], Array<TestimonialItem>>,
  'getVisaEligibilityResults' : ActorMethod<[], Array<VisaEligibilityResult>>,
  'getVisibleGalleryEntries' : ActorMethod<[], Array<GalleryEntry>>,
  'getWebsiteTheme' : ActorMethod<[], WebsiteTheme>,
  'reorderCountries' : ActorMethod<
    [string, Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'reorderPartnerUniversities' : ActorMethod<
    [SessionToken, Array<RecordId>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setBeOurPartnerContent' : ActorMethod<
    [SessionToken, BeOurPartnerContent],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setServiceDetail' : ActorMethod<
    [SessionToken, ServiceDetailContent],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    SubmissionResult
  >,
  'submitCounselingBooking' : ActorMethod<
    [string, string, string, Array<string>, string, string],
    SubmissionResult
  >,
  'submitDemoClassBooking' : ActorMethod<
    [string, string, string, string, string],
    SubmissionResult
  >,
  'submitImmigrationConsultation' : ActorMethod<
    [string, string, string, string, string, string],
    SubmissionResult
  >,
  'submitJobApplication' : ActorMethod<[JobApplicationInput], JobApplication>,
  'submitPartnerInquiry' : ActorMethod<
    [BeOurPartnerInquiryInput],
    SubmissionResult
  >,
  'submitVisaEligibility' : ActorMethod<
    [string, string, bigint, string, bigint, string, bigint],
    SubmissionResult
  >,
  'subscribeNewsletter' : ActorMethod<[string], SubmissionResult>,
  'toggleBlogPostPublish' : ActorMethod<
    [SessionToken, RecordId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'toggleGalleryEntryVisibility' : ActorMethod<
    [SessionToken, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateAboutPageContent' : ActorMethod<
    [SessionToken, AboutPageContent],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateBatchTiming' : ActorMethod<
    [
      SessionToken,
      string,
      RecordId,
      {
        'endDate' : string,
        'enrolled' : bigint,
        'capacity' : bigint,
        'schedule' : string,
        'startDate' : string,
      },
    ],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateBlogPost' : ActorMethod<
    [SessionToken, RecordId, BlogPostInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateContactInfo' : ActorMethod<
    [string, ContactInfo],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCountryDetailBySlug' : ActorMethod<
    [SessionToken, CountryDetailContent],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCountryInfo' : ActorMethod<
    [string, CountryInfo],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateEvent' : ActorMethod<
    [string, RecordId, EventItemInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateFooterContent' : ActorMethod<
    [string, FooterContent],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateFreeCounselingContent' : ActorMethod<
    [string, FreeCounselingContent],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateGalleryEntry' : ActorMethod<
    [SessionToken, bigint, GalleryEntryInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateHeroContent' : ActorMethod<
    [string, HeroContent],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateHomeSectionsContent' : ActorMethod<
    [string, HomeSectionsContent],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateImmigrationVisa' : ActorMethod<
    [SessionToken, ImmigrationVisa],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateJobOpening' : ActorMethod<
    [SessionToken, bigint, JobOpeningInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateLeadershipMembers' : ActorMethod<
    [SessionToken, Array<LeadershipMember>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateLifeAtValmikiContent' : ActorMethod<
    [string, LifeAtValmikiContent],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePageContent' : ActorMethod<
    [SessionToken, string, PageContent],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePageHeroContent' : ActorMethod<
    [string, PageHeroContent],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePartnerUniversity' : ActorMethod<
    [SessionToken, RecordId, PartnerUniversity],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateService' : ActorMethod<
    [string, RecordId, ServiceItemInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateStudyAbroadContent' : ActorMethod<
    [SessionToken, StudyAbroadContent],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateTeamMember' : ActorMethod<
    [string, RecordId, TeamMemberInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateTestPrepExam' : ActorMethod<
    [SessionToken, TestPrepExam],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateTestimonial' : ActorMethod<
    [string, RecordId, TestimonialInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateWebsiteTheme' : ActorMethod<
    [string, WebsiteTheme],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'verifyAdminToken' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];